server:
  port: 8000

afas:
  fhir:
    next-url-encryption-key: change-me
    subscription:
      hmacKey: 123456
      enabled: true
      pageSize: 50
  mongodb:
    uri: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017/?socketTimeoutMS=360000&connectTimeoutMS=360000}
    dbname: ${DB_NAME:afassample}

  publicUrl: http://localhost:8000/fhir