#ryuk.container.image=testcontainers/ryuk:0.3.3
#tinyimage.container.image=alpine:3.14
#sshd.container.image=testcontainers/sshd:1.0.0
ryuk.container.image=614q518g.gra7.container-registry.ovh.net/dockerhub-proxy/testcontainers/ryuk:0.3.3
tinyimage.container.image=614q518g.gra7.container-registry.ovh.net/dockerhub-proxy/alpine:3.14
sshd.container.image=614q518g.gra7.container-registry.ovh.net/dockerhub-proxy/testcontainers/sshd:1.0.0
ryuk.disabled=true
